name: TrabalhoTeste

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # --- WINDOWS ---
      - name: Instalar dependências e compilar (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Compilar no Windows
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: gcc -Wall -Wextra -O2 main.c -o programa.exe

      - name: Executar programa no Windows com entrada simulada
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          echo -e "João\n10\n" | ./programa.exe

      # --- UBUNTU ---
      - name: Instalar GCC no Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y gcc

      - name: Compilar no Ubuntu
        if: runner.os == 'Linux'
        run: gcc -Wall -Wextra -O2 main.c -o programa

      - name: Executar programa no Ubuntu com entrada simulada
        if: runner.os == 'Linux'
        run: |
          echo -e "João\n10\n" | ./programa
